name: "Revamp dependencies"
description: "Dependencies revamping"
inputs:
  reviewers:
    description: Comma seperated names of reviewers for created PR
    required: false
    default: ''
  dry_run:
    description: Dry run action
    default: 'true'
    required: false
  working_directory:
    description: "Working directory, defaults to GITHUB_WORKSPACE"
    required: false
    default: ${{ github.workspace }}


runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      working-directory: ${{ inputs.working_directory }}
      with:
        with_checks: 'false'
        # ToDo: Re-enable cache when https://github.com/actions/setup-python/issues/361 is fixed
        poetry_cache_enabled: 'false'

    - name: Revamp dependencies
      shell: bash
      id: revamp-dependencies
      run: |
        poetry run actions_helper revamp-dependencies \
          --dry-run ${{ inputs.dry_run }} \
          --reviewers ${{ inputs.reviewers }}