name: "Revamp dependencies"
description: "Dependencies revamping"
inputs:
  reviewers:
    description: Comma seperated names of reviewers for created PR
    required: false
    default: ''
  dry_run:
    description: Dry run action
    default: 'true'
    required: false
  working_directory:
    description: "Working directory, defaults to GITHUB_WORKSPACE"
    required: false
    default: ${{ github.workspace }}

  ssh_key:
    description: "SSH key to use for private repositories"
    required: false


runs:
  using: "composite"

  steps:
    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      with:
        working_directory: ${{ github.action_path }}
        with_checks: 'false'
        poetry_cache_enabled: 'false'

    # Step 3: Use the first environment
    - id: action-virtual-path
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        VIRTUAL_ENV_PATH=$(find ~/.cache/pypoetry/virtualenvs -type d -maxdepth 1 | tail -n 1)
        echo VIRTUAL_ENV_PATH
        echo "venv-path=$VIRTUAL_ENV_PATH" >> $GITHUB_OUTPUT

    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      with:
        working_directory: ${{ inputs.working_directory }}
        with_checks: 'false'
        poetry_cache_enabled: 'false'
        ssh_key: ${{ inputs.ssh_key }}

    - name: Revamp dependencies
      shell: bash
      id: revamp-dependencies
      working-directory: ${{ inputs.working_directory }}
      run: |
        ACTION_VIRTUAL_ENV_PATH=${{ steps.action-virtual-path.outputs.venv-path }}
        
        ls $ACTION_VIRTUAL_ENV_PATH/bin
        export PATH="$ACTION_VIRTUAL_ENV_PATH/bin:$PATH"
        
        if [ ! -z "${{ inputs.ssh_key }}" ]; then
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ inputs.ssh_key }}"
        fi

        actions_helper revamp-dependencies \
          --dry-run ${{ inputs.dry_run }} \
          --reviewers ${{ inputs.reviewers }} \
          --revamp-dir ${{ inputs.working_directory }}
