name: "Revamp dependencies"
description: "Dependencies revamping"
inputs:
  reviewers:
    description: Comma seperated names of reviewers for created PR
    required: false
    default: ''
  dry_run:
    description: Dry run action
    default: 'true'
    required: false
  working_directory:
    description: "Working directory, defaults to GITHUB_WORKSPACE"
    required: false
    default: ${{ github.workspace }}

  ssh_key:
    description: SSH key
    required: false
  ssh_auth_sock:
    description: SSH auth socket
    required: false
    default: /tmp/ssh_agent.sock


runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      with:
        working_directory: ${{ github.action_path }}
        with_checks: 'false'
        # ToDo: Re-enable cache when https://github.com/actions/setup-python/issues/361 is fixed
        poetry_cache_enabled: 'false'

#    - name: Setup SSH agent
#      if: inputs.ssh_key != ''
#      id: setup-ssh-agent
#      run: |
#        export SSH_AUTH_SOCK=${{ inputs.ssh_auth_sock }}
#        ssh-agent -a ${SSH_AUTH_SOCK} > /dev/null
#        ssh-add - <<< "${{ inputs.ssh_key }}"
#        echo "ssh-auth-sock=${SSH_AUTH_SOCK}" >> $GITHUB_OUTPUT
#      shell: bash

    - name: Revamp dependencies
      shell: bash
      id: revamp-dependencies
      working-directory: ${{ github.action_path }}
      run: |
        cd ${{ inputs.working_directory }}
        poetry run --directory ${{ github.action_path }} actions_helper revamp-dependencies \
          --dry-run ${{ inputs.dry_run }} \
          --reviewers ${{ inputs.reviewers }}
