name: "Revamp dependencies"
description: "Dependencies revamping"
inputs:
  reviewers:
    description: Comma seperated names of reviewers for created PR
    required: false
    default: ''
  dry_run:
    description: Dry run action
    default: 'true'
    required: false


runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
        ssh-key: '${{ secrets.WORKFLOW_DEPLOY_KEY }}'

    - name: Setup Python + Poetry
      uses: moneymeets/action-setup-python-poetry@master
      with:
        working_directory: ${{ github.action_path }}
        with_checks: 'false'
        # ToDo: Re-enable cache when https://github.com/actions/setup-python/issues/361 is fixed
        poetry_cache_enabled: 'false'

    - name: Revamp dependencies
      shell: bash
      id: revamp-dependencies
      working-directory: ${{ github.action_path }}
      run: |
        poetry run actions_helper revamp-dependencies \
          --dry-run ${{ inputs.dry_run }}
          --reviewers ${{ inputs.reviewers }}